export interface TemplateInfo {
  id: string;
  name: string;
  category: 'standard' | 'premium';
  price: number;
  tag: string;
  industry: string;
  description: string;
  isPopular?: boolean;
}

export const TEMPLATES_LIST: TemplateInfo[] = [
  {
    id: 'AcademicResearchTemplate',
    name: 'Academic Research',
    category: 'standard',
    price: 2,
    tag: 'Investigación & Educación',
    industry: 'Educación / Investigación',
    description: 'Estructura editorial clásica ideal para docentes, investigadores y perfiles universitarios.',
  },
  {
    id: 'ATSDirectClassicTemplate',
    name: 'ATS Direct Classic',
    category: 'standard',
    price: 2,
    tag: '100% ATS Approved',
    industry: 'Multisectorial',
    description: 'Formato limpio garantizado para lectura óptima por filtros automatizados de RRHH.',
  },
  {
    id: 'ATSMinimalTemplate',
    name: 'ATS Minimal',
    category: 'standard',
    price: 2,
    tag: '100% ATS Approved',
    industry: 'Administrativo / Legal',
    description: 'Jerarquía tipográfica minimalista sin elementos gráficos que obstaculicen escáneres.',
  },
  {
    id: 'CharcoalCompactTemplate',
    name: 'Charcoal Compact',
    category: 'standard',
    price: 2,
    tag: 'Compacto & Eficiente',
    industry: 'Administración / Logística',
    description: 'Aprovechamiento máximo del espacio en 1 sola página Carta con tonos carbón nítidos.',
  },
  {
    id: 'CommercialSalesTemplate',
    name: 'Commercial Sales',
    category: 'standard',
    price: 2,
    tag: 'Ventas & Negocios',
    industry: 'Ventas / Retail / Comercial',
    description: 'Enfocado en métricas de cumplimiento, metas alcanzadas y gestión de cuentas claves.',
  },
  {
    id: 'CustomerCareTemplate',
    name: 'Customer Care Pro',
    category: 'standard',
    price: 2,
    tag: 'Servicio & Call Center',
    industry: 'Servicio al Cliente / BPO',
    description: 'Estructura clara resaltando comunicación, resolución de conflictos e idiomas.',
  },
  {
    id: 'EmeraldCleanTemplate',
    name: 'Emerald Clean',
    category: 'standard',
    price: 2,
    tag: 'Fresco & Ordenado',
    industry: 'Salud / Administración',
    description: 'Toques de verde esmeralda con distribución equilibrada entre perfil y experiencia.',
  },
  {
    id: 'HospitalityTourismTemplate',
    name: 'Hospitality & Tourism',
    category: 'standard',
    price: 2,
    tag: 'Turismo & Hotelería',
    industry: 'Turismo / Gastronomía',
    description: 'Diseñado para el sector turístico de RD, enfatizando idiomas, servicio y dinamismo.',
  },
  {
    id: 'LegalCounselTemplate',
    name: 'Legal Counsel',
    category: 'standard',
    price: 2,
    tag: 'Sobrio & Formal',
    industry: 'Derecho / Asuntos Legales',
    description: 'Estilo formal y sobrio optimizado para abogados, consultores y gestores legales.',
  },
  {
    id: 'LogisticsProTemplate',
    name: 'Logistics & Ops Pro',
    category: 'standard',
    price: 2,
    tag: 'Cadena de Suministro',
    industry: 'Logística / Cadena de Mando',
    description: 'Organización por bloques para destacar experiencia operativa y certificaciones.',
  },
  {
    id: 'MedicalHealthTemplate',
    name: 'Medical & Health Care',
    category: 'standard',
    price: 2,
    tag: 'Sector Salud',
    industry: 'Medicina / Enfermería',
    description: 'Distribución institucional perfecta para médicos, personal de enfermería y salud.',
  },
  {
    id: 'NavyCorporateTemplate',
    name: 'Navy Corporate',
    category: 'standard',
    price: 2,
    tag: 'Corporativo Clásico',
    industry: 'Finanzas / Banca',
    description: 'Azul marino clásico que transmite solvencia y profesionalismo en el sector corporativo.',
  },
  {
    id: 'OperationsLeadTemplate',
    name: 'Operations Lead',
    category: 'standard',
    price: 2,
    tag: 'Gestión de Operaciones',
    industry: 'Operaciones / Planta',
    description: 'Prioriza logros de eficiencia, manejo de personal y supervisión de procesos.',
  },
  {
    id: 'SlateModernTemplate',
    name: 'Slate Modern',
    category: 'standard',
    price: 2,
    tag: 'Moderno Neutro',
    industry: 'Tecnología / Servicios',
    description: 'Líneas limpias en gris pizarra con alta legibilidad para cualquier industria.',
  },
  {
    id: 'TechDeveloperTemplate',
    name: 'Tech & Code Developer',
    category: 'standard',
    price: 2,
    tag: 'Software & IT',
    industry: 'Tecnología / Software',
    description: 'Optimizado para ingenieros de software, analistas y perfiles técnicos.',
  },
  {
    id: 'CorporateArchTemplate',
    name: 'Corporate Arch Prestige',
    category: 'premium',
    price: 5,
    tag: 'Arco Ejecutivo',
    industry: 'Alta Gerencia / Directiva',
    description: 'Diseño imponente con columna lateral en tono navy y base en arco dorado brillante.',
    isPopular: true,
  },
  {
    id: 'DarkMonolithTemplate',
    name: 'Dark Monolith Elite',
    category: 'premium',
    price: 5,
    tag: 'Alto Impacto Visual',
    industry: 'Consultoría / Tecnología',
    description: 'Estética oscura de lujo para perfiles senior que buscan dejar un impacto memorable.',
  },
  {
    id: 'ExecutiveGoldTemplate',
    name: 'Executive Gold',
    category: 'premium',
    price: 5,
    tag: 'Más Vendida',
    industry: 'Gerencia / Administración',
    description: 'Acentos dorados premium con fotografía enmarcada y bloques ejecutivos dinámicos.',
    isPopular: true,
  },
  {
    id: 'FintechAnalyticsTemplate',
    name: 'Fintech Analytics',
    category: 'premium',
    price: 5,
    tag: 'Finanzas & Data',
    industry: 'Fintech / Análisis de Datos',
    description: 'Aspecto moderno y estructurado con indicadores visuales para habilidades cuantitativas.',
  },
  {
    id: 'MinimalLuxeTemplate',
    name: 'Minimal Luxe',
    category: 'premium',
    price: 5,
    tag: 'Elegancia Pura',
    industry: 'Diseño / Moda / Arquitectura',
    description: 'Espaciado blanco editorial y tipografía impecable para creativos de alto nivel.',
  },
  {
    id: 'NordicMinimalTemplate',
    name: 'Nordic Minimal Pro',
    category: 'premium',
    price: 5,
    tag: 'Estilo Escandinavo',
    industry: 'Diseño / Marketing',
    description: 'Líneas puras y balance impecable inspirado en el diseño escandinavo.',
  },
  {
    id: 'PortfolioShowcaseTemplate',
    name: 'Portfolio Showcase',
    category: 'premium',
    price: 5,
    tag: 'Creativos & Artistas',
    industry: 'Diseño Gráfico / Multimedia',
    description: 'Incluye espacio destacado para enlaces directos a portafolios y proyectos visuales.',
  },
  {
    id: 'SeniorConsultantTemplate',
    name: 'Senior Consultant',
    category: 'premium',
    price: 5,
    tag: 'Consultoría Estratégica',
    industry: 'Consultoría / Negocios',
    description: 'Formato de dos columnas optimizado para proyectos de alto alcance y asesorías.',
  },
  {
    id: 'StrategicDirectorTemplate',
    name: 'Strategic Director',
    category: 'premium',
    price: 5,
    tag: 'Nivel C-Suite',
    industry: 'Directores / C-Level',
    description: 'Estructura sólida y elegante creada exclusivamente para posiciones de liderazgo.',
  },
  {
    id: 'StudioHorizonTemplate',
    name: 'Studio Horizon',
    category: 'premium',
    price: 5,
    tag: 'Estudio Creativo',
    industry: 'Publicidad / Innovación',
    description: 'Encabezado dinámico con barra de contacto horizontal y paleta de alto impacto.',
  },
];